# Generated by Django 4.1.1 on 2022-09-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(default=None, max_length=300)),
                ('status', models.CharField(default=None, max_length=50)),
                ('level', models.CharField(default=None, max_length=50)),
                ('matric', models.CharField(default=None, max_length=50)),
                ('gender', models.CharField(default=None, max_length=50)),
                ('date_of_birth', models.CharField(default=None, max_length=50)),
                ('bio', models.CharField(default=None, max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('profile_background_picture', models.ImageField(blank=True, null=True, upload_to='profile_background_picture/')),
            ],
        ),
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_Code', models.CharField(default=None, max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='Spreadsheets/')),
                ('staff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='calebapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_list', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='calebapp.roster')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roster_owner', to='calebapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_Code', models.CharField(default=None, max_length=30)),
                ('lecturer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calebapp.profile')),
                ('students', models.ManyToManyField(default=1, related_name='student_list', to='calebapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PeerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calebapp.profile')),
                ('sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_sender', to='calebapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Groupmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=None, max_length=3000)),
                ('time_sent', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='calebapp.group')),
                ('sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_message_sender', to='calebapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='calebapp.profile'),
        ),
        migrations.CreateModel(
            name='Chatmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=None, max_length=3000)),
                ('time_sent', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='calebapp.chat')),
                ('sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sender', to='calebapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calebapp.profile'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default=None, max_length=100)),
                ('book_file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('book_creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calebapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calebapp.profile')),
                ('friend_list', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='friend_list', to='calebapp.profile')),
            ],
        ),
    ]
