# Generated by Django 4.1.1 on 2022-09-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0002_alter_profile_bio_alter_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(default='-- - --', max_length=50),
        ),
    ]
