# Generated by Django 4.1.1 on 2022-09-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0003_book_time_sent_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
