# Generated by Django 4.1.1 on 2022-09-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0004_book_book_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
