# Generated by Django 4.1.1 on 2022-09-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0005_alter_book_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
