# Generated by Django 4.1.1 on 2022-09-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0006_alter_book_time_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='friend_list',
        ),
        migrations.AddField(
            model_name='peer',
            name='friend_list',
            field=models.ManyToManyField(default=1, related_name='friend_list', to='calebapp.profile'),
        ),
    ]
