# Generated by Django 4.1.1 on 2022-09-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0008_remove_peer_friend_list_profile_friend_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend_list',
            field=models.ManyToManyField(default=1, related_name='friend_list', to='calebapp.peer'),
        ),
    ]
