# Generated by Django 4.1.1 on 2022-09-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0010_remove_profile_friend_list_peer_friend_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='friend_list',
            field=models.ManyToManyField(default=[0], related_name='friend_list', to='calebapp.profile'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='students',
            field=models.ManyToManyField(default=[0], related_name='student_list', to='calebapp.profile'),
        ),
    ]
