# Generated by Django 4.1.1 on 2022-10-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0012_remove_chat_users_chat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calebapp.chat'),
        ),
    ]
