# Generated by Django 4.1.1 on 2022-10-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0013_alter_chatmessage_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='time_sent',
        ),
    ]
