# Generated by Django 4.1.1 on 2022-10-07 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0014_remove_chatmessage_time_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 20, 19, 15, 797295)),
        ),
    ]
