# Generated by Django 4.1.1 on 2022-11-14 22:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0015_chatmessage_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 23, 47, 54, 474798)),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_name', models.CharField(default=None, max_length=100)),
                ('pod_file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('pod_description', models.FileField(blank=True, null=True, upload_to='books/')),
                ('pod_downloads', models.IntegerField(default=0)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('pod_creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calebapp.profile')),
            ],
        ),
    ]
