# Generated by Django 4.1.1 on 2022-11-15 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0016_alter_chatmessage_time_sent_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 30, 14, 281839)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='pod_description',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
