# Generated by Django 4.1.1 on 2022-11-15 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0017_alter_chatmessage_time_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 21, 46, 8, 56109)),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_subject', models.CharField(default=None, max_length=100)),
                ('news_content', models.CharField(default=None, max_length=5000)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('news_creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calebapp.profile')),
            ],
        ),
    ]
