# Generated by Django 4.1.1 on 2022-11-19 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0019_alter_book_time_sent_alter_chatmessage_time_sent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='course_Code',
            new_name='course_code',
        ),
        migrations.AddField(
            model_name='registration',
            name='course_description',
            field=models.CharField(default=None, max_length=3000),
        ),
        migrations.AddField(
            model_name='registration',
            name='course_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 9, 47, 19, 132950)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 9, 47, 19, 124901)),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 9, 47, 19, 132950)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 9, 47, 19, 132950)),
        ),
    ]
