# Generated by Django 4.1.1 on 2022-11-19 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0020_rename_course_code_registration_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 12, 2, 35, 584142)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 12, 2, 35, 577621)),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 12, 2, 35, 584142)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 12, 2, 35, 584142)),
        ),
    ]
