# Generated by Django 4.1.1 on 2022-11-19 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0021_registration_course_length_alter_book_time_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 11, 24, 569042)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 11, 24, 569042)),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 11, 24, 584669)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 11, 24, 569042)),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='calebapp.profile')),
            ],
        ),
    ]
