# Generated by Django 4.1.1 on 2022-11-19 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0022_alter_book_time_sent_alter_chatmessage_time_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 12, 2, 463490)),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 12, 2, 447861)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 12, 2, 447861)),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 12, 2, 447861)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 12, 2, 447861)),
        ),
    ]
