# Generated by Django 4.1.1 on 2022-11-19 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0023_receipt_time_sent_alter_book_time_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='collection_date',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='purpose',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 26, 40, 783066)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 26, 40, 783066)),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 26, 40, 783066)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 26, 40, 783066)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 22, 26, 40, 798687)),
        ),
    ]
