# Generated by Django 4.1.1 on 2022-11-27 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0025_alter_book_time_sent_alter_chatmessage_time_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheet',
            name='course_Code',
        ),
        migrations.RemoveField(
            model_name='spreadsheet',
            name='file',
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='datasheets/'),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='department',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='description',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='info',
            field=models.FileField(blank=True, null=True, upload_to='info/'),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='level',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='missing_result',
            field=models.FileField(blank=True, null=True, upload_to='missing_result/'),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='mode_of_entry',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='number_of_courses',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='probation',
            field=models.FileField(blank=True, null=True, upload_to='probation/'),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='session',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='spreadsheet',
            field=models.FileField(blank=True, null=True, upload_to='spreadsheets/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 14, 1, 41, 295341)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 14, 1, 41, 279714)),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 14, 1, 41, 295341)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 14, 1, 41, 295341)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 14, 1, 41, 295341)),
        ),
    ]
