# Generated by Django 4.1.1 on 2022-11-27 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0026_remove_spreadsheet_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_picture',
            field=models.ImageField(blank=True, null=True, upload_to='group_picture/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 15, 27, 46, 812932)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 15, 27, 46, 802864)),
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 15, 27, 46, 812932)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 15, 27, 46, 812932)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 15, 27, 46, 822999)),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(default=[0], to='calebapp.profile'),
        ),
    ]
