# Generated by Django 4.1.1 on 2022-12-03 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0027_group_group_picture_alter_book_time_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_creator',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_creator', to='calebapp.profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_description',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default='undefined', max_length=50),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='semester',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 19, 40, 476245)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 19, 40, 476245)),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calebapp.group'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 19, 40, 476245)),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 19, 40, 491871)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 19, 40, 491871)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_background_picture',
            field=models.ImageField(blank=True, default='./media/profile_picture/1234.jpg', null=True, upload_to='profile_background_picture/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='./media/profile_picture/1234.jpg', null=True, upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 19, 40, 491871)),
        ),
    ]
