# Generated by Django 4.1.1 on 2022-12-03 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0028_group_group_creator_group_group_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 20, 1, 12599)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 20, 1, 7527)),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 20, 1, 7527)),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 20, 1, 17608)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 20, 1, 17608)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 20, 1, 22645)),
        ),
    ]
