# Generated by Django 4.1.1 on 2022-12-03 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0029_alter_book_time_sent_alter_chatmessage_time_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 20, 8, 92645)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 20, 8, 79533)),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 20, 8, 82565)),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 20, 8, 97655)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 20, 8, 97655)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 10, 20, 8, 102688)),
        ),
    ]
