# Generated by Django 4.1.1 on 2022-12-07 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0034_alter_book_time_sent_alter_chatmessage_time_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 9, 9, 2, 712494)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 9, 9, 2, 712494)),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 9, 9, 2, 712494)),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 9, 9, 2, 728121)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 9, 9, 2, 712494)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_background_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_background_picture/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 9, 9, 2, 728121)),
        ),
    ]
