# Generated by Django 4.1.1 on 2022-12-08 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0042_alter_book_time_sent_alter_chatmessage_database_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='database_time',
        ),
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 19, 59, 48, 56672)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 19, 59, 48, 56672)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 19, 59, 48, 56672)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 19, 59, 48, 56672)),
        ),
    ]
