# Generated by Django 3.2.16 on 2022-12-16 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calebapp', '0043_remove_chatmessage_database_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 4, 55, 10, 391237)),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 4, 55, 10, 392228)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 4, 55, 10, 391740)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 4, 55, 10, 411482)),
        ),
    ]
